# Generated by Django 5.2 on 2025-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeassociation',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('ndeye', 'Ndèye Daara')], max_length=10, null=True),
        ),
    ]
