# Generated by Django 5.2 on 2025-06-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0002_demandeassociation_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='device',
            name='longitude',
        ),
    ]
