# Generated by Django 5.2 on 2025-06-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0003_remove_device_latitude_remove_device_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='esp_id',
            new_name='id_esp32',
        ),
    ]
