# Generated by Django 5.2 on 2025-06-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0004_rename_esp_id_device_id_esp32'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id_esp32',
            new_name='esp_id',
        ),
    ]
