# Generated by Django 5.2 on 2025-06-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0005_rename_id_esp32_device_esp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='esp_id',
            new_name='id_esp32',
        ),
    ]
