# Generated by Django 5.2 on 2025-06-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0006_rename_esp_id_device_id_esp32'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetoken',
            old_name='esp',
            new_name='id_esp32',
        ),
    ]
