# Generated by Django 5.2 on 2025-06-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0007_rename_esp_devicetoken_id_esp32'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id_esp32',
            new_name='esp_id',
        ),
        migrations.RenameField(
            model_name='devicetoken',
            old_name='id_esp32',
            new_name='esp',
        ),
    ]
