# Generated by Django 5.2 on 2025-07-01 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0008_rename_id_esp32_device_esp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='appareil',
        ),
        migrations.AlterField(
            model_name='enfant',
            name='id_esp32',
            field=models.OneToOneField(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackingtalibe.device', verbose_name="Id de l'appareil"),
        ),
    ]
