# Generated by Django 5.2 on 2025-07-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0009_remove_enfant_appareil_alter_enfant_id_esp32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='id_esp32',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackingtalibe.device', verbose_name="Id de l'appareil"),
        ),
    ]
