# Generated by Django 5.2 on 2025-07-01 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0010_alter_enfant_id_esp32'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='appareil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackingtalibe.device'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='id_esp32',
            field=models.CharField(max_length=100, unique=True, verbose_name="Id de l'appareil"),
        ),
    ]
