# Generated by Django 5.2 on 2025-07-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0011_enfant_appareil_alter_enfant_id_esp32'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude_daara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude_daara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rayon_securite',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
