# Generated by Django 5.2 on 2025-07-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0013_remove_customuser_latitude_daara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude_daara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude_daara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rayon_securite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
