# Generated by Django 5.2 on 2025-07-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0014_customuser_latitude_daara_customuser_longitude_daara_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latitude_daara',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude_daara',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rayon_securite',
        ),
    ]
