# Generated by Django 5.2 on 2025-08-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0015_remove_customuser_latitude_daara_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='téléphone',
            new_name='telephone',
        ),
    ]
