# Generated by Django 5.2 on 2025-08-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0016_rename_téléphone_customuser_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rayon_securite_metres', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='enfant',
            name='daara',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='trackingtalibe.daara'),
            preserve_default=False,
        ),
    ]
