# Generated by Django 5.2 on 2025-08-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingtalibe', '0017_daara_enfant_daara'),
    ]

    operations = [
        migrations.AddField(
            model_name='daara',
            name='serigne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daaras', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
